# Generated by scripts/generate_dialogue_audio.py.
extends RefCounted

const CLIPS := {
	"芽芽\n哎呀！土地怎么都这样了！！\n": preload("res://assets/audio/dialogue/yaya_intro_01.wav"),
	"芽芽\n作物没有水分都枯萎了，我们要赶紧给他们浇浇水呀\n": preload("res://assets/audio/dialogue/yaya_intro_02.wav"),
	"芽芽\n现在每块土壤的湿度都不一样，我们每个植物浇水量可能会有差异，看看以前大家是怎么浇水的吧\n": preload("res://assets/audio/dialogue/yaya_intro_03.wav"),
	"芽芽\n每一种作物都得到了适合自己的照顾。世界目标已经完成，现在请书书根据真实学习路线归档。\n这次规则为什么能照顾不同作物？": preload("res://assets/audio/dialogue/yaya_complete.wav"),
	"叮当师傅\n先做两个小实验，把数组、缺口和水量在世界里一一对应起来。\n两个数组为什么要使用同一个 i？": preload("res://assets/audio/dialogue/dingdang_workshop.wav"),
	"叮当师傅\n两个数组要用同一个 i 找到同一块土地。现在还没有失败 Run，我不会假装某一行已经出错。\n": preload("res://assets/audio/dialogue/dingdang_goal.wav"),
	"叮当师傅\n胡萝卜土地正确，但1号番茄漏浇、5号番茄水量不足，6号土豆反而多浇。它们有什么共同点？\n": preload("res://assets/audio/dialogue/dingdang_hint_0.wav"),
	"叮当师傅\n循环、分支和输出位置都在工作。请只检查 gap 这一行里的“目标值”从哪里来。\n": preload("res://assets/audio/dialogue/dingdang_hint_1.wav"),
	"叮当师傅\n两个数组用相同下标记录同一块土地；i 变化时，当前值和目标值要一起变化。\n": preload("res://assets/audio/dialogue/dingdang_hint_2.wav"),
	"叮当师傅\n局部支架：目标数组[同一下标] - 当前数组[同一下标]。\n": preload("res://assets/audio/dialogue/dingdang_hint_3.wav"),
	"书书\n我只记录已经发生的事实：代码变化、使用过的提示，以及是否接受过 AI 修改。\n你想把哪一步带到下一次挑战？": preload("res://assets/audio/dialogue/shushu_archive.wav"),
}
