"""Provider-neutral skill build and artifact publication primitives.

The package is intentionally safe to import without assembling an HTTP server,
database adapter, migrator, worker, or runtime Sandbox.  Backend applications
compose these primitives through the public names exported here.
"""

from .pipeline import (
    CPP20_SAFE_V1_FLAGS,
    CPP20_SAFE_V1_PROFILE,
    ArtifactIntegrityError,
    ArtifactPublicationError,
    BuildDiagnostic,
    BuildResourceLimits,
    CommandExecutionError,
    CommandOutputLimitError,
    CommandResult,
    CommandRunner,
    CommandTimeoutError,
    CommandUnavailableError,
    ContentAddressedArtifactPublisher,
    CppTestCase,
    CppTestSuite,
    DigestPinnedDockerCppBuilder,
    DockerBuildFailure,
    DockerBuildResult,
    DockerTestResult,
    PublishedArtifact,
    SourceBundleValidationError,
    SubprocessCommandRunner,
    ValidatedSourceBundle,
    ValidatedSourceFile,
    canonical_source_bundle_sha256,
    validate_source_bundle,
)

__all__ = [
    "ArtifactIntegrityError",
    "ArtifactPublicationError",
    "BuildDiagnostic",
    "BuildResourceLimits",
    "CPP20_SAFE_V1_FLAGS",
    "CPP20_SAFE_V1_PROFILE",
    "CommandExecutionError",
    "CommandOutputLimitError",
    "CommandResult",
    "CommandRunner",
    "CommandTimeoutError",
    "CommandUnavailableError",
    "ContentAddressedArtifactPublisher",
    "CppTestCase",
    "CppTestSuite",
    "DigestPinnedDockerCppBuilder",
    "DockerBuildFailure",
    "DockerBuildResult",
    "DockerTestResult",
    "PublishedArtifact",
    "SourceBundleValidationError",
    "SubprocessCommandRunner",
    "ValidatedSourceBundle",
    "ValidatedSourceFile",
    "canonical_source_bundle_sha256",
    "validate_source_bundle",
]
